ui/Receita.Web/Models/ErrorViewModel.cs
namespace Receita.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ui/Receita.Web/ViewModels/CategoriaViewModel.cs
namespace Receita.Web.ViewModels
{
    public class CategoriaViewModel
    {
        public int Id { get; set; }

        public string Titulo { get; set; }

        public string Descricao { get; set; }
    }
}

ui/Receita.Web/ViewModels/ErrorViewModel.cs
namespace Receita.Web.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ui/Receita.Web/ViewModels/ReceitaViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Threading.Tasks;

namespace Receita.Web.ViewModels
{
    public class ReceitaViewModel
    {
        public int Id { get; set; }

        [Display(Name = "Usuário")]
        public int IdUsuario { get; set; }

        [Display(Name = "Categoria")]
        public int IdCategoria { get; set; }

        [Display(Name = "Título")]
        public string Titulo { get; set; }

        [Display(Name = "Descrição")]
        public string Descricao { get; set; }

        public string Ingredientes { get; set; }

        [Display(Name = "Modo De Preparo")]
        public string ModoDePreparo { get; set; }

        public string Foto { get; set; }

        [Display(Name = "Foto")]
        public IFormFile FotoUpload { get; set; }

        public string Tag { get; set; }

        public bool Status { get; set; }

        public async Task<ReceitaViewModel> ConverterArquivoParaBase64() 
        {
            if (FotoUpload != null)
            {
                using (var ms = new MemoryStream()) 
                {
                    await FotoUpload.CopyToAsync(ms);

                    var fotoBytes = ms.ToArray();

                    Foto = Convert.ToBase64String(fotoBytes);
                }
            }

            return this;
        }

        public ReceitaViewModel() { }
    }
}

ui/Receita.Web/ViewModels/UsuarioAdmViewModel.cs
namespace Receita.Web.ViewModels
{
    public class UsuarioAdmViewModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public int IdGrupo { get; set; }
    }
}

ui/Receita.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Receita.Web.ViewModels;
using System.Diagnostics;

namespace Receita.Web.Controllers
{
    public class HomeController : Controller
    {
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ui/Receita.Web/Controllers/ReceitaController.cs
using Microsoft.AspNetCore.Mvc;
using Receita.Web.HttpClients.Interfaces;
using Receita.Web.ViewModels;
using System.Threading.Tasks;

namespace Receita.Web.Controllers
{
    public class ReceitaController : Controller
    {
        private readonly IReceitaClient _receitaClient;
        private readonly ICategoriaClient _categoriaClient;
        private readonly IUsuarioAdmClient _usuarioAdmClient;

        public ReceitaController(IReceitaClient receitaClient, 
            ICategoriaClient categoriaClient,
            IUsuarioAdmClient usuarioAdmClient)
        {
            _receitaClient = receitaClient;
            _categoriaClient = categoriaClient;
            _usuarioAdmClient = usuarioAdmClient;
        }

        // GET: Receita
        public async Task<IActionResult> Index()
        {
            var receitas = await _receitaClient.GetReceitasAsync();

            return View(receitas);
        }

        // Get: Receita/PorCategoria/5
        public async Task<IActionResult> PorCategoria(int id)
        {
            var receitas = await _receitaClient.GetPorCategoriaAsync(id);

            return View("Index", receitas);
        }

        // GET: Receita/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var receita = await _receitaClient.GetPorIdAsync(id);

            return View(receita);
        }

        // GET: Receita/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.Categorias = await _categoriaClient.GetCategoriasToViewAsync();
            ViewBag.Usuarios = await _usuarioAdmClient.GetAllToViewAsync();

            return View();
        }

        // POST: Receita/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ReceitaViewModel receitaViewModel)
        {
            try
            {
                var receita = await receitaViewModel.ConverterArquivoParaBase64();

                await _receitaClient.SalvarAsync(receita);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Receita/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var receita = await _receitaClient.GetPorIdAsync(id);

            ViewBag.Categorias = await _categoriaClient.GetCategoriasToViewAsync();
            ViewBag.Usuarios = await _usuarioAdmClient.GetAllToViewAsync();

            return View("Create", receita);
        }

        // GET: Receita/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var response = await _receitaClient.DeleteAsync(id);

            if (response)
                TempData["msg"] = "Receita removida com sucesso!";
            else
                TempData["erro"] = "Problemas ao remover receita";

            TempData.Keep();

            return RedirectToAction(nameof(List));
        }

        public async Task<IActionResult> List()
        {
            var receitas = await _receitaClient.GetReceitasAsync();

            return View(receitas);
        }
    }
}

ui/Receita.Web/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Receita.Web.HttpClients.Interfaces;
using System.Threading.Tasks;

namespace Receita.Web.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly ICategoriaClient _categoriaClient;

        public MenuViewComponent(ICategoriaClient categoriaClient)
        {
            _categoriaClient = categoriaClient;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categorias = await _categoriaClient.GetCategoriasAsync();

            return View(categorias);
        }
    }
}

ui/Receita.Web/Views/Receita/Create.cshtml
@model ReceitaViewModel
@{
    ViewData["Title"] = "Cadastrar";
}

<div class="container mt-5">
    <div class="row">
        <div class="col-6">
            <h3>Detalhes da Receita</h3>
            @using (Html.BeginForm("Create", "Receita", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-group">
                    @Html.LabelFor(p => p.Titulo)
                    <div class="input-group mb-3">
                        <div class="input-group">
                            <span class="input-group-text"><i class="fa fa-heading"></i></span>
                            @Html.TextBoxFor(p => p.Titulo, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.Descricao)
                    <div class="input-group mb-3">
                        <div class="input-group">
                            <span class="input-group-text"><i class="fa fa-highlighter"></i></span>
                            @Html.TextAreaFor(p => p.Descricao, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.Ingredientes)
                    <div class="input-group mb-3">
                        <div class="input-group">
                            <span class="input-group-text"><i class="fa fa-egg"></i></span>
                            @Html.TextAreaFor(p => p.Ingredientes, new { @class = "form-control", rows = "10" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.ModoDePreparo)
                    <div class="input-group mb-3">
                        <div class="input-group">
                            <span class="input-group-text"><i class="fa fa-list-alt"></i></span>
                            @Html.TextAreaFor(p => p.ModoDePreparo, new { @class = "form-control", rows = "10" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.Tag)
                    <div class="input-group mb-3">
                        <div class="input-group">
                            <span class="input-group-text"><i class="fa fa-bars"></i></span>
                            @Html.TextBoxFor(p => p.Tag, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.FotoUpload)
                    <div class="input-group mb-3">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fa fa-camera"></i></span>
                            </div>
                            <div class="custom-file">
                                <input asp-for="FotoUpload" type="file" class="custom-file-input" aria-describedby="inputText" />
                                <label class="custom-file-label" for="inputText">Selecione a foto da receita</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.IdCategoria)
                    <div class="input-group mb-3">
                        <div class="input-group">
                            <span class="input-group-text"><i class="fa fa-book"></i></span>
                            <select asp-for="IdCategoria" asp-items="ViewBag.Categorias" class="form-control"></select>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(p => p.IdUsuario)
                    <div class="input-group mb-3">
                        <div class="input-group">
                            <span class="input-group-text"><i class="fa fa-user"></i></span>
                            <select asp-for="IdUsuario" asp-items="ViewBag.Usuarios" class="form-control"></select>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Salvar" class="btn btn-primary" />
                </div>
            }
        </div>
        <div class="col-6">
            <h3>Imagem Atual</h3>
            @if (Model?.Foto != null)
            {
                <img src="data:image/png;base64,@Model.Foto" class="img-fluid" />
            }
            else 
            {
                <p>Nenhuma imagem cadastrada</p>
            }
        </div>
    </div>
</div>

ui/Receita.Web/Views/Receita/Details.cshtml
@model ReceitaViewModel
@{
    ViewData["Title"] = "Detalhes";
}

<div class="container mt-5">
    <section class="row">
        <div class="col-12">
            <h1>@Model.Titulo</h1>
            <img src="data:image/png;base64,@Model.Foto" class="img-fluid" />
            <p>@Model.Ingredientes</p>
            <p>@Model.ModoDePreparo</p>
            <a href="/">Voltar</a>
        </div>        
    </section>
</div>

ui/Receita.Web/Views/Receita/Index.cshtml
@model IEnumerable<ReceitaViewModel>

@{
    ViewData["Title"] = "Receitas Maravilhosas";
}

<div class="container mt-5">
    <div class="row">
        @foreach (var receita in Model)
        {
            <div class="col-6">
                <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    <div class="col p-4 d-flex flex-column position-static">
                        <strong class="d-inline-block mb-2 text-primary">@receita.Tag</strong>
                        <h3 class="mb-0">@receita.Titulo</h3>
                        <p class="card-text mb-auto">@receita.Descricao</p>
                        <a href="Receita/Details/?id=@receita.Id" class="stretched-link">Ler</a>
                    </div>
                    <div class="col-auto d-none d-lg-block">
                        <img src="data:image/png;base64,@receita.Foto" class="bd-placeholder-img" width="200" height="250" />
                    </div>
                </div>
            </div>
        }
    </div>
</div>

ui/Receita.Web/Views/Receita/List.cshtml
@model IEnumerable<ReceitaViewModel>
@{
    ViewData["Title"] = "Lista de Receitas";
}

<div class="container mt-5">
    <div class="row">
        <div class="col-12 col-lg-12">
            @if (TempData["msg"] != null)
            {
                <div class="alert alert-success" role="alert">
                    @TempData["msg"]
                </div>
            }
            @if (TempData["erro"] != null)
            {
                <div class="alert alert-danger" role="alert">
                    @TempData["erro"]
                </div>
            }
        </div>
    </div>
    <table class="table table-borderless table-striped table-responsive-sm">
        <thead>
            <tr>
                <th>Id</th>
                <th>Título</th>
                <th>Descrição</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var receita in Model)
            {
                var modalId = $"remove{receita.Id}";

                <tr>
                    <td>@receita.Id</td>
                    <td>@receita.Titulo</td>
                    <td>@receita.Descricao</td>
                    <td>
                        <a class="mr-1" href="Edit/?id=@receita.Id" title="Editar"><i class="fa fa-edit"></i></a>
                        <a href="javascript:;" data-toggle="modal" data-target="#@modalId"><i class="fa fa-trash text-danger" title="Excluir"></i></a>

                        <!-- Modal  -->
                        <div class="modal fade" id="@modalId" tabindex="-1" role="dialog">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title"><i class="fa fa-exclamation-triangle text-danger"></i> Atenção!</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Você deseja realmente remover a receita @receita.Titulo ?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <a href="Delete/?id=@receita.Id" class="btn btn-success">Sim</a>
                                        <button type="button" class="btn btn-danger" data-dismiss="modal">Não</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

ui/Receita.Web/Views/Shared/Components/Menu/Default.cshtml
@model IEnumerable<CategoriaViewModel>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container">
        <div class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" asp-controller="Receita" asp-action="Index">Receitas</a>
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown-user" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user-cog"></i> Administração</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown-user">
                        <a class="dropdown-item" asp-area="" asp-controller="Receita" asp-action="Create">Criar</a>
                        <a class="dropdown-item" asp-area="" asp-controller="Receita" asp-action="List">Consultar</a>
                    </div>
                </li>
                @foreach (var categoria in Model)
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Receita" asp-action="PorCategoria" asp-route-id="@categoria.Id" title="@categoria.Descricao">@categoria.Titulo<span class="sr-only">(current)</span></a>
                    </li>
                }
            </ul>
        </div>
    </div>
</nav>

ui/Receita.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Receitas</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />
</head>
<body>
    <main role="main">
        @await Component.InvokeAsync("Menu")
        <div class="row mb-2" style="height: 20px;"></div>
        @RenderBody()
    </main>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Receitas
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>